#!/bin/bash

# Prepares the temporary folder for the Docker build process.
# Copies all files of workspace packages required in the first docker layer: installation (e.g.  package.json, yarn.lock)
# The relevant files are copied preserving the folder structure of the packages.
# The Dockerfile can copy them all in a single step from the output folder.
#
# $1 - output folder (name or relative path), default: .docker-packages
#
# Examples
#
#   prepare-packages.sh temp/docker-files
#
# Returns the exit code of the last command executed in debug mode or 0
#   otherwise.




DIR=$(readlink -f "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )")
ROOT_DIR=$(readlink -f "$DIR/..")

OUT_DIR_NAME="${1-".docker-packages"}" # path is referenced in dockerfiles
OUT_DIR_NAME="${OUT_DIR_NAME/$ROOT_DIR\//}" # ensure the path is relative by removing the absolute parent path

OUT_DIR_PATH=$(readlink -f "$ROOT_DIR/$OUT_DIR_NAME")



# --------------------------------------------------------------------
#
#   This is where we collect relevant files
#
# --------------------------------------------------------------------

find_relevant_files() {
    find "$ROOT_DIR/$1" -maxdepth 2 \( -name package.json -o -name yarn.lock -o -name lerna.json \) -not -path "*node_modules*" -not -path "*bower_components*" -not -path "*$OUT_DIR_NAME*"
}

workspace_files=( $(find_relevant_files .) )
dev_files=( $(find_relevant_files __dev__) )
client_files=( $(find_relevant_files client) )
relevant_files=( "${workspace_files[@]}" "${dev_files[@]}" "${client_files[@]}" )

echo "Preparing"
for file in ${relevant_files[*]}
do
    file_name="$( basename "$file" )"
    package_dir="$( dirname "$file" )"
    package_path="${package_dir/$ROOT_DIR\//}"

    mkdir -p "$OUT_DIR_PATH/$package_path"
    cp "$package_dir/$file_name" "$OUT_DIR_PATH/$package_path/$file_name"
done

echo "# Do not edit the contents of this folder\n\n
This folder was generated by \`prepare-packages.sh\`.  \
It contains the workspace package files that our \
Dockerfiles will copy in a single step" > "$OUT_DIR_NAME/README.MD"
